### ISSUE TITLE
Error in 5ghz patch

### ISSUE THREAD

**Issue by farwayer** [corenel/XPS9550-OSX#1]
ty for sharing configs 👍 

5ghz patch must be (you have invalid find data):
```
                <key>Find</key>
                <data>
                QYP8/3QsSA==
                </data>
                <key>Name</key>
                <string>AirPortBrcm4360</string>
                <key>Replace</key>
                <data>
                ZscGVVPrKw==
```

**Comment by corenel** [comment]
Do you mean that `QYP8/3QsSA==` in `config.plist` isn't correct?

**Comment by farwayer** [comment]
All ok now. You already fixed it in this commit https://github.com/corenel/XPS9550-OSX/commit/99ad383625707f659e322aec39c4ddfdb1eafda2#diff-cd9999831fd158fd3c775b44b00907f2L265
