### ISSUE TITLE
DSDT is getting me kernel panic on Sierra

### ISSUE THREAD

**Issue by Lukypie** [corenel/XPS9550-OSX#2]
I dont know how but I can't compile the .dsl you provided, and the compiled aml just gave me infinite kernel panics.

**Comment by corenel** [comment]
You should dump your own DSDT and SSDT in Clover, and patch them on your own following the guide.
Or now you can use Clover hot-patch just as described [here](https://www.tonymacx86.com/threads/guide-using-clover-to-hotpatch-acpi.200137/). And that's included in my repo.
