### ISSUE TITLE
Hi.Does your touchpad work well ?

### ISSUE THREAD

**Issue by Supertramplee** [corenel/XPS9550-OSX#3]
Thanks for your guide.But,I found my touchpad doesn't work well, such as "three fingers to move the window".Also,about the keyboard , home,end,pgup,pgdn doesn't work.......What about u ?

**Comment by corenel** [comment]
It seems that macOS Sierra modified lots of things, and some function of Touchpad can't work, such as three fingers tap.
However, Home/End/PgUp/PgDn works fine in my laptop.
Maybe we should wait for driver to be updated.
