### ISSUE TITLE
The Tonymacx86 page was removed- Anyone have a backup?

### ISSUE THREAD

**Issue by outlassn** [corenel/XPS9550-OSX#4]
Tonymacx86 page https://www.tonymacx86.com/threads/guide-wip-dell-xps-15-9550-skylake-gtx960m-ssd-via-clover-uefi.192598/ removed, Need help :(

**Comment by corenel** [comment]
Maybe you could look at [this backup](http://buyhackintosh.com/guide-dell-xps-15-9550-skylake-gtx960m-ssd-via-clover-uefi/), but I don't know whether it's up-to-date.

**Comment by outlassn** [comment]
Shit, i forgot I even kept this open-- Turns out the guy moved to Insanelymac forums, and he has re-uploaded it there since- Thanks for looking for the backup though :) Means alot 👍 

Feel free to close the issue, http://www.insanelymac.com/forum/topic/319766-dell-xps-9550-detailled-1011-guide/ is the new page.
