### ISSUE TITLE
how do I change my SMBIOS

### ISSUE THREAD

**Issue by soulomoon** [corenel/XPS9550-OSX#5]
Than you for your guidance I was able to get my dell 5510 to work under Sierra, but I was stuck when trying to follow your HDMI patch because I don't how to change my SMBIOS,
I would really appreciate some enlightening.

**Comment by corenel** [comment]
If you use `Macbook9,1` SMBIOS, the HDMI output is already fine.
If you want to use `iMac17,1` SMBIOS, you should change it in `config.plist`. Clover Configurator is a useful tool for generating SMBIOS.

**Comment by soulomoon** [comment]
I won't boot to my OS X after modify the SMBIOS in cloverconfigurater

**Comment by soulomoon** [comment]
iMac 14 get me to work just fine with hdmi now for dell 5510 i7 6820 hd530
