### ISSUE TITLE
HDMI don't have audio...

### ISSUE THREAD

**Issue by ii404msn** [corenel/XPS9550-OSX#6]
I use `MBP13,3` SMBIOS, HDMI don't work, so I edit Info.plist.
But only Video, Audio only work on computer...
Do your HDMI work fine?

**Comment by corenel** [comment]
Sorry, I only use HDMI for video ouput, audio part is not tested. It seems a common problem for Hackintosh.
May you you could try `MB9,1` or `iMac17,1` SMBIOS. Or [syscl's tutorial](http://www.insanelymac.com/forum/topic/319211-guide-fix-skylake-hdmidp-output/) for fixing HDMI/DP output.
