### ISSUE TITLE
关于声音问题开机失效

### ISSUE THREAD

**Issue by Jeremyye114** [corenel/XPS9550-OSX#7]
不知道你的会不会这样，VoodooPS2Daemon 的或者是黑手的Apple HDA都会在一段开机时间内失效变灰色，用万能驱动但耳机却无法使用~~

**Comment by corenel** [comment]
抱歉，我一般用的是蓝牙的耳机或者USB接解码器，都很正常，所以没怎么关注过AppleHDA的问题。
现在无论是aDummy还是修改后的AppleHDA都有些问题，对于这个问题似乎没有完美的解决方案。

**Comment by Jeremyye114** [comment]
@corenel ooo，这样啊，非常感谢你的回复~~等大神有更好的完善方案

**Comment by Jeremyye114** [comment]
@corenel https://github.com/darkhandz/XPS15-9550-Sierra/issues/67  可以试试这个万能声卡，测试几天也没有问题～朋友的xps15也是没有问题，耳机mic 外置都可以～先装在SLE上，然后修复权限有声音再装到EFI里面，LICENSE也要按，自己试试～
